// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("asmauthextension")
	ScopeName = "github.com/dev7a/otelcol-ext-asmauth"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
