// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("asmauth")
	ScopeName = "github.com/dev7a/asmauthextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
